[workspace]
authors = ["Simone Massaro <simone.massaro@mone27.net>"]
channels = ["conda-forge"]
name = "point-cloud-formats"
platforms = ["linux-64", "win-64","osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python-pdal = ">=3.5.3,<4"
python = "3.14.*"
ipykernel = ">=7.1.0,<8"
ipywidgets = ">=8.1.8,<9"
pyprojroot = ">=0.3.0,<0.4"
plotnine = ">=0.15.2,<0.16"
polars = ">=1.36.1,<2"
pyarrow = ">=22.0.0,<23"
tqdm = ">=4.67.1,<5"
